# Generated by Django 3.2.8 on 2021-12-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
