# Generated by Django 3.2.8 on 2021-12-08 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20211202_1500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locations',
            name='url',
        ),
    ]
