# Generated by Django 3.2.8 on 2021-12-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20211209_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.FloatField(max_length=7),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.FloatField(max_length=7),
        ),
    ]
