# Generated by Django 3.2.8 on 2021-12-09 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20211209_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locations',
            name='latitude',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='locations',
            name='longitude',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
