# Generated by Django 3.2.8 on 2021-12-02 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diver_pk', models.IntegerField(blank=True, null=True)),
                ('location_pk', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(max_length=1)),
                ('trip_name', models.CharField(max_length=250)),
                ('checklist_1', models.BooleanField(default=False)),
                ('checklist_2', models.BooleanField(default=False)),
                ('checklist_3', models.BooleanField(default=False)),
                ('checklist_4', models.BooleanField(default=False)),
                ('checklist_5', models.BooleanField(default=False)),
                ('checklist_6', models.BooleanField(default=False)),
                ('checklist_7', models.BooleanField(default=False)),
                ('checklist_8', models.BooleanField(default=False)),
                ('checklist_9', models.BooleanField(default=False)),
                ('checklist_10', models.BooleanField(default=False)),
            ],
        ),
    ]
