# Generated by Django 3.2.8 on 2021-12-10 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_alter_trips_diver_pk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trips',
            name='diver_pk',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
